-- Checklist assignment no longer picks a one-off date — an employee is
-- linked to a template as a standing assignment, and the actual daily
-- `checklists` instance is auto-generated by generate_due_checklists()
-- (scheduled via pg_cron below) whenever the company's visit_days/visit_time
-- comes around, matching the recurring schedule already set on Companies.
create table checklist_assignments (
  id uuid primary key default gen_random_uuid(),
  template_id uuid not null references checklist_templates(id) on delete cascade,
  company_id uuid not null references companies(id) on delete cascade,
  employee_id uuid not null references employees(id) on delete cascade,
  admin_note text,
  created_at timestamptz not null default now(),
  unique (template_id, employee_id)
);
create index checklist_assignments_company_id_idx on checklist_assignments(company_id);
create index checklist_assignments_employee_id_idx on checklist_assignments(employee_id);

alter table checklist_assignments enable row level security;

create policy checklist_assignments_admin_all on checklist_assignments for all to authenticated
  using (is_admin()) with check (is_admin());
create policy checklist_assignments_self_select on checklist_assignments for select to authenticated
  using (employee_id = auth.uid());

-- Runs on a schedule (see cron.schedule below): for every standing
-- assignment whose company's visit_days includes today and whose
-- visit_time has just come up, creates today's checklists row for that
-- employee — unless one already exists (so re-running mid-window is safe).
create or replace function generate_due_checklists()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  today_dow int := extract(dow from current_date);
  today date := current_date;
begin
  insert into checklists (template_id, company_id, site, employee_id, assigned_date, areas, status, admin_note)
  select
    ca.template_id,
    ca.company_id,
    ct.site,
    ca.employee_id,
    today,
    ct.areas,
    'pending',
    ca.admin_note
  from checklist_assignments ca
  join checklist_templates ct on ct.id = ca.template_id
  join companies c on c.id = ca.company_id
  where today_dow = any(c.visit_days)
    and c.visit_time is not null
    and now()::time >= c.visit_time
    and now()::time < c.visit_time + interval '15 minutes'
    and not exists (
      select 1 from checklists existing
      where existing.template_id = ca.template_id
        and existing.employee_id = ca.employee_id
        and existing.assigned_date = today
    );
end;
$$;

revoke execute on function generate_due_checklists() from public;
revoke execute on function generate_due_checklists() from anon;
revoke execute on function generate_due_checklists() from authenticated;

-- Requires the pg_cron extension (Database -> Extensions in the Supabase
-- dashboard, usually already available). Runs every 5 minutes; the 15-minute
-- match window above means a company's visit_time is caught even if a run
-- is skipped once.
create extension if not exists pg_cron with schema extensions;

select cron.schedule(
  'generate-due-checklists',
  '*/5 * * * *',
  $$select generate_due_checklists()$$
);
